In [1]:
import numpy as np

## Training Data

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

x_shape = inputs.shape

In [4]:
# weights and biases
weights = np.random.rand(2,3)
biases = np.random.rand(15,2)
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.04547965 0.43656896 0.22192613]
 [0.14072419 0.68398837 0.13658688]]
Biases:
[[0.86878022 0.32465477]
 [0.68433965 0.20083081]
 [0.56334415 0.02034368]
 [0.86998893 0.58299082]
 [0.53410171 0.35914525]
 [0.87242058 0.82409858]
 [0.28354012 0.72886816]
 [0.14424472 0.77529036]
 [0.46537306 0.66316169]
 [0.90669345 0.49329725]
 [0.62717471 0.22734118]
 [0.3526427  0.24143437]
 [0.95905836 0.63787986]
 [0.58680335 0.90606614]
 [0.15558753 0.42304183]]


In [5]:
# Define the model
def model(x):
    return x @ np.transpose(weights) + biases

In [6]:
# Generate predictions
preds = model(inputs)

In [7]:
# Compare with targets
print("Predictions : ", preds, sep="\n")
print("Targets : ",targets, sep="\n")

Predictions : 
[[ 42.98173853  62.29797692]
 [ 57.44432851  81.93926852]
 [ 75.89202965 111.83982836]
 [ 32.49264543  49.40207226]
 [ 61.11764663  85.29307906]
 [ 42.98537889  62.79742073]
 [ 57.04352897  82.46730587]
 [ 75.47293022 112.59477503]
 [ 32.08802956  49.48224313]
 [ 61.49023836  85.42723106]
 [ 42.74013302  62.20066333]
 [ 57.11263155  81.97987207]
 [ 76.28774386 112.45736454]
 [ 32.20945985  49.72514758]
 [ 60.73913245  85.35697564]]
Targets : 
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [8]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

In [9]:
# Compute loss
loss = mse(preds, targets)
print(loss)

1317.597107717867


In [10]:
# compute gradients
biases_grad = (preds-targets)*2/x_shape[0]
weights_grad = (np.matmul(np.transpose((preds-targets)),inputs))*2/x_shape[0]

print("weights_grad:",weights_grad, sep="\n")
print("biases_grad:",biases_grad, sep="\n")

weights_grad:
[[-3486.45373795 -4931.60258853 -2855.70318763]
 [-2045.34956948 -3052.93421113 -1849.97900428]]
biases_grad:
[[-1.7357682  -1.02693641]
 [-3.1407562  -2.54143086]
 [-5.74772938 -2.82135622]
 [ 1.39901939  1.65360964]
 [-5.58431378 -4.49425613]
 [-1.73528282 -0.9603439 ]
 [-3.19419614 -2.47102588]
 [-5.8036093  -2.72069666]
 [ 1.34507061  1.66429908]
 [-5.53463489 -4.47636919]
 [-1.76798226 -1.03991156]
 [-3.18498246 -2.53601706]
 [-5.69496749 -2.73901806]
 [ 1.36126131  1.69668634]
 [-5.63478234 -4.48573658]]


## Adjust weights

In [11]:
# Adjust weights
weights -= weights_grad * 1e-5
biases -= biases_grad * 1e-5

In [12]:
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.08034419 0.48588498 0.25048316]
 [0.16117768 0.71451771 0.15508667]]
Biases:
[[0.86879758 0.32466504]
 [0.68437106 0.20085623]
 [0.56340163 0.0203719 ]
 [0.86997494 0.58297428]
 [0.53415756 0.35919019]
 [0.87243793 0.82410819]
 [0.28357206 0.72889287]
 [0.14430276 0.77531757]
 [0.46535961 0.66314504]
 [0.90674879 0.49334202]
 [0.62719239 0.22735158]
 [0.35267455 0.24145973]
 [0.95911531 0.63790725]
 [0.58678974 0.90604917]
 [0.15564388 0.42308669]]


In [13]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

810.4459396670554


In [14]:
# repeating same for 200 times
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    
    biases_grad = ((((inputs@np.transpose(weights))+biases)-targets))*2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights))+biases)-targets)),inputs))*2/x_shape[0]

    weights -= weights_grad * 1e-5
    biases -= biases_grad * 1e-5

In [15]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

35.37399546040093


In [16]:
# Print predictions
print(preds)

[[ 58.13701474  70.91105317]
 [ 80.81951415  96.99684654]
 [120.98104011 138.98275997]
 [ 24.57643434  40.67620639]
 [ 97.52366869 111.13169387]
 [ 58.14065412  71.41036315]
 [ 80.41882202  97.5247424 ]
 [120.56205298 139.73750434]
 [ 24.17192689  40.75635577]
 [ 97.89616058 111.26580993]
 [ 57.89547397  70.81376566]
 [ 80.48790608  97.03743922]
 [121.37664828 139.60013067]
 [ 24.29332465  40.99919514]
 [ 97.14525594 111.19557333]]


In [17]:
# Print targets
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
